@FlightsDiggingApp_HostAddress = http://localhost:5136

GET {{FlightsDiggingApp_HostAddress}}/getroundtrip/
Accept: application/json

GET {{FlightsDiggingApp_HostAddress}}/getairports/
Accept: application/json


###
